server:
  port: 8006 #8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: provider-mongodb
  data:
    mongodb:
      uri: mongodb://10.124.102.42:27017/values
